# Site settings
name: Liwugang's Blog
email: liwugang@163.com
author: Li Wugang
url: https://liwugang.github.io/
resume_site: https://liwugang.github.io/
github: https://github.com/liwugang/
baseurl: ""
description: Patient && Courage
meta_description: liwugang;个人博客;
motto: 
banner: 
gems: [jekyll-paginate]
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: liwugang

# Build settings
markdown: kramdown

baidu_analysis: 1d2fe4c4c213d17757e0b1a94713ead0